version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_demo
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    restart: always

  flask:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/demo
    depends_on:
      - postgres